// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "trendservice/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// AggregatorService is an autogenerated mock type for the AggregatorService type
type AggregatorService struct {
	mock.Mock
}

type AggregatorService_Expecter struct {
	mock *mock.Mock
}

func (_m *AggregatorService) EXPECT() *AggregatorService_Expecter {
	return &AggregatorService_Expecter{mock: &_m.Mock}
}

// Snapshot provides a mock function with no fields
func (_m *AggregatorService) Snapshot() *domain.TopSnapshot {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 *domain.TopSnapshot
	if rf, ok := ret.Get(0).(func() *domain.TopSnapshot); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TopSnapshot)
		}
	}

	return r0
}

// AggregatorService_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type AggregatorService_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
func (_e *AggregatorService_Expecter) Snapshot() *AggregatorService_Snapshot_Call {
	return &AggregatorService_Snapshot_Call{Call: _e.mock.On("Snapshot")}
}

func (_c *AggregatorService_Snapshot_Call) Run(run func()) *AggregatorService_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AggregatorService_Snapshot_Call) Return(_a0 *domain.TopSnapshot) *AggregatorService_Snapshot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AggregatorService_Snapshot_Call) RunAndReturn(run func() *domain.TopSnapshot) *AggregatorService_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// NewAggregatorService creates a new instance of AggregatorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAggregatorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AggregatorService {
	mock := &AggregatorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
