// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// CacheClient is an autogenerated mock type for the CacheClient type
type CacheClient struct {
	mock.Mock
}

type CacheClient_Expecter struct {
	mock *mock.Mock
}

func (_m *CacheClient) EXPECT() *CacheClient_Expecter {
	return &CacheClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *CacheClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CacheClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type CacheClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *CacheClient_Expecter) Close() *CacheClient_Close_Call {
	return &CacheClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *CacheClient_Close_Call) Run(run func()) *CacheClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CacheClient_Close_Call) Return(_a0 error) *CacheClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CacheClient_Close_Call) RunAndReturn(run func() error) *CacheClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Del provides a mock function with given fields: ctx, keys
func (_m *CacheClient) Del(ctx context.Context, keys ...string) error {
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = rf(ctx, keys...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CacheClient_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type CacheClient_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *CacheClient_Expecter) Del(ctx interface{}, keys ...interface{}) *CacheClient_Del_Call {
	return &CacheClient_Del_Call{Call: _e.mock.On("Del",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *CacheClient_Del_Call) Run(run func(ctx context.Context, keys ...string)) *CacheClient_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *CacheClient_Del_Call) Return(_a0 error) *CacheClient_Del_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CacheClient_Del_Call) RunAndReturn(run func(context.Context, ...string) error) *CacheClient_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *CacheClient) Get(ctx context.Context, key string) (string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CacheClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CacheClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheClient_Expecter) Get(ctx interface{}, key interface{}) *CacheClient_Get_Call {
	return &CacheClient_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *CacheClient_Get_Call) Run(run func(ctx context.Context, key string)) *CacheClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CacheClient_Get_Call) Return(_a0 string, _a1 error) *CacheClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CacheClient_Get_Call) RunAndReturn(run func(context.Context, string) (string, error)) *CacheClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *CacheClient) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CacheClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type CacheClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CacheClient_Expecter) Ping(ctx interface{}) *CacheClient_Ping_Call {
	return &CacheClient_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *CacheClient_Ping_Call) Run(run func(ctx context.Context)) *CacheClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CacheClient_Ping_Call) Return(_a0 error) *CacheClient_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CacheClient_Ping_Call) RunAndReturn(run func(context.Context) error) *CacheClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// SAdd provides a mock function with given fields: ctx, key, members
func (_m *CacheClient) SAdd(ctx context.Context, key string, members ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, key)
	_ca = append(_ca, members...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SAdd")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) error); ok {
		r0 = rf(ctx, key, members...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CacheClient_SAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SAdd'
type CacheClient_SAdd_Call struct {
	*mock.Call
}

// SAdd is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - members ...interface{}
func (_e *CacheClient_Expecter) SAdd(ctx interface{}, key interface{}, members ...interface{}) *CacheClient_SAdd_Call {
	return &CacheClient_SAdd_Call{Call: _e.mock.On("SAdd",
		append([]interface{}{ctx, key}, members...)...)}
}

func (_c *CacheClient_SAdd_Call) Run(run func(ctx context.Context, key string, members ...interface{})) *CacheClient_SAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *CacheClient_SAdd_Call) Return(_a0 error) *CacheClient_SAdd_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CacheClient_SAdd_Call) RunAndReturn(run func(context.Context, string, ...interface{}) error) *CacheClient_SAdd_Call {
	_c.Call.Return(run)
	return _c
}

// SIsMember provides a mock function with given fields: ctx, key, member
func (_m *CacheClient) SIsMember(ctx context.Context, key string, member interface{}) (bool, error) {
	ret := _m.Called(ctx, key, member)

	if len(ret) == 0 {
		panic("no return value specified for SIsMember")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) (bool, error)); ok {
		return rf(ctx, key, member)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) bool); ok {
		r0 = rf(ctx, key, member)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}) error); ok {
		r1 = rf(ctx, key, member)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CacheClient_SIsMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SIsMember'
type CacheClient_SIsMember_Call struct {
	*mock.Call
}

// SIsMember is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - member interface{}
func (_e *CacheClient_Expecter) SIsMember(ctx interface{}, key interface{}, member interface{}) *CacheClient_SIsMember_Call {
	return &CacheClient_SIsMember_Call{Call: _e.mock.On("SIsMember", ctx, key, member)}
}

func (_c *CacheClient_SIsMember_Call) Run(run func(ctx context.Context, key string, member interface{})) *CacheClient_SIsMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *CacheClient_SIsMember_Call) Return(_a0 bool, _a1 error) *CacheClient_SIsMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CacheClient_SIsMember_Call) RunAndReturn(run func(context.Context, string, interface{}) (bool, error)) *CacheClient_SIsMember_Call {
	_c.Call.Return(run)
	return _c
}

// SMembers provides a mock function with given fields: ctx, key
func (_m *CacheClient) SMembers(ctx context.Context, key string) ([]string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for SMembers")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CacheClient_SMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SMembers'
type CacheClient_SMembers_Call struct {
	*mock.Call
}

// SMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheClient_Expecter) SMembers(ctx interface{}, key interface{}) *CacheClient_SMembers_Call {
	return &CacheClient_SMembers_Call{Call: _e.mock.On("SMembers", ctx, key)}
}

func (_c *CacheClient_SMembers_Call) Run(run func(ctx context.Context, key string)) *CacheClient_SMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CacheClient_SMembers_Call) Return(_a0 []string, _a1 error) *CacheClient_SMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CacheClient_SMembers_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *CacheClient_SMembers_Call {
	_c.Call.Return(run)
	return _c
}

// SRem provides a mock function with given fields: ctx, key, members
func (_m *CacheClient) SRem(ctx context.Context, key string, members ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, key)
	_ca = append(_ca, members...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SRem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) error); ok {
		r0 = rf(ctx, key, members...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CacheClient_SRem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SRem'
type CacheClient_SRem_Call struct {
	*mock.Call
}

// SRem is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - members ...interface{}
func (_e *CacheClient_Expecter) SRem(ctx interface{}, key interface{}, members ...interface{}) *CacheClient_SRem_Call {
	return &CacheClient_SRem_Call{Call: _e.mock.On("SRem",
		append([]interface{}{ctx, key}, members...)...)}
}

func (_c *CacheClient_SRem_Call) Run(run func(ctx context.Context, key string, members ...interface{})) *CacheClient_SRem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *CacheClient_SRem_Call) Return(_a0 error) *CacheClient_SRem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CacheClient_SRem_Call) RunAndReturn(run func(context.Context, string, ...interface{}) error) *CacheClient_SRem_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, ttl
func (_m *CacheClient) Set(ctx context.Context, key string, value interface{}, ttl time.Duration) error {
	ret := _m.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = rf(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CacheClient_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type CacheClient_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - ttl time.Duration
func (_e *CacheClient_Expecter) Set(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *CacheClient_Set_Call {
	return &CacheClient_Set_Call{Call: _e.mock.On("Set", ctx, key, value, ttl)}
}

func (_c *CacheClient_Set_Call) Run(run func(ctx context.Context, key string, value interface{}, ttl time.Duration)) *CacheClient_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *CacheClient_Set_Call) Return(_a0 error) *CacheClient_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CacheClient_Set_Call) RunAndReturn(run func(context.Context, string, interface{}, time.Duration) error) *CacheClient_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewCacheClient creates a new instance of CacheClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheClient {
	mock := &CacheClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
