// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Consumer is an autogenerated mock type for the Consumer type
type Consumer struct {
	mock.Mock
}

type Consumer_Expecter struct {
	mock *mock.Mock
}

func (_m *Consumer) EXPECT() *Consumer_Expecter {
	return &Consumer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *Consumer) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Consumer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Consumer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Consumer_Expecter) Close() *Consumer_Close_Call {
	return &Consumer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Consumer_Close_Call) Run(run func()) *Consumer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Consumer_Close_Call) Return(_a0 error) *Consumer_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Consumer_Close_Call) RunAndReturn(run func() error) *Consumer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with given fields: ctx
func (_m *Consumer) Run(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Consumer_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Consumer_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Consumer_Expecter) Run(ctx interface{}) *Consumer_Run_Call {
	return &Consumer_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *Consumer_Run_Call) Run(run func(ctx context.Context)) *Consumer_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Consumer_Run_Call) Return(_a0 error) *Consumer_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Consumer_Run_Call) RunAndReturn(run func(context.Context) error) *Consumer_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewConsumer creates a new instance of Consumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Consumer {
	mock := &Consumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
