// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Stoplist is an autogenerated mock type for the Stoplist type
type Stoplist struct {
	mock.Mock
}

type Stoplist_Expecter struct {
	mock *mock.Mock
}

func (_m *Stoplist) EXPECT() *Stoplist_Expecter {
	return &Stoplist_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, words
func (_m *Stoplist) Add(ctx context.Context, words ...string) error {
	_va := make([]interface{}, len(words))
	for _i := range words {
		_va[_i] = words[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = rf(ctx, words...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stoplist_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Stoplist_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - words ...string
func (_e *Stoplist_Expecter) Add(ctx interface{}, words ...interface{}) *Stoplist_Add_Call {
	return &Stoplist_Add_Call{Call: _e.mock.On("Add",
		append([]interface{}{ctx}, words...)...)}
}

func (_c *Stoplist_Add_Call) Run(run func(ctx context.Context, words ...string)) *Stoplist_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *Stoplist_Add_Call) Return(_a0 error) *Stoplist_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Stoplist_Add_Call) RunAndReturn(run func(context.Context, ...string) error) *Stoplist_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function with given fields: ctx, query
func (_m *Stoplist) Has(ctx context.Context, query string) bool {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Stoplist_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type Stoplist_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *Stoplist_Expecter) Has(ctx interface{}, query interface{}) *Stoplist_Has_Call {
	return &Stoplist_Has_Call{Call: _e.mock.On("Has", ctx, query)}
}

func (_c *Stoplist_Has_Call) Run(run func(ctx context.Context, query string)) *Stoplist_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Stoplist_Has_Call) Return(_a0 bool) *Stoplist_Has_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Stoplist_Has_Call) RunAndReturn(run func(context.Context, string) bool) *Stoplist_Has_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *Stoplist) List(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Stoplist_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Stoplist_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Stoplist_Expecter) List(ctx interface{}) *Stoplist_List_Call {
	return &Stoplist_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *Stoplist_List_Call) Run(run func(ctx context.Context)) *Stoplist_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Stoplist_List_Call) Return(_a0 []string, _a1 error) *Stoplist_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Stoplist_List_Call) RunAndReturn(run func(context.Context) ([]string, error)) *Stoplist_List_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx, words
func (_m *Stoplist) Remove(ctx context.Context, words ...string) error {
	_va := make([]interface{}, len(words))
	for _i := range words {
		_va[_i] = words[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = rf(ctx, words...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stoplist_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type Stoplist_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - words ...string
func (_e *Stoplist_Expecter) Remove(ctx interface{}, words ...interface{}) *Stoplist_Remove_Call {
	return &Stoplist_Remove_Call{Call: _e.mock.On("Remove",
		append([]interface{}{ctx}, words...)...)}
}

func (_c *Stoplist_Remove_Call) Run(run func(ctx context.Context, words ...string)) *Stoplist_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *Stoplist_Remove_Call) Return(_a0 error) *Stoplist_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Stoplist_Remove_Call) RunAndReturn(run func(context.Context, ...string) error) *Stoplist_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// NewStoplist creates a new instance of Stoplist. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoplist(t interface {
	mock.TestingT
	Cleanup(func())
}) *Stoplist {
	mock := &Stoplist{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
