global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'trend-service'
    static_configs:
      - targets: ['trending:8080']
        labels:
          service: 'trend-service'
          environment: 'local'
