// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "trendservice/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Aggregator is an autogenerated mock type for the Aggregator type
type Aggregator struct {
	mock.Mock
}

type Aggregator_Expecter struct {
	mock *mock.Mock
}

func (_m *Aggregator) EXPECT() *Aggregator_Expecter {
	return &Aggregator_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: query, userID, eventTsUnix, nowUnix, maxSkew
func (_m *Aggregator) Add(query string, userID string, eventTsUnix int64, nowUnix int64, maxSkew int64) bool {
	ret := _m.Called(query, userID, eventTsUnix, nowUnix, maxSkew)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, int64, int64, int64) bool); ok {
		r0 = rf(query, userID, eventTsUnix, nowUnix, maxSkew)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Aggregator_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Aggregator_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - query string
//   - userID string
//   - eventTsUnix int64
//   - nowUnix int64
//   - maxSkew int64
func (_e *Aggregator_Expecter) Add(query interface{}, userID interface{}, eventTsUnix interface{}, nowUnix interface{}, maxSkew interface{}) *Aggregator_Add_Call {
	return &Aggregator_Add_Call{Call: _e.mock.On("Add", query, userID, eventTsUnix, nowUnix, maxSkew)}
}

func (_c *Aggregator_Add_Call) Run(run func(query string, userID string, eventTsUnix int64, nowUnix int64, maxSkew int64)) *Aggregator_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(int64), args[3].(int64), args[4].(int64))
	})
	return _c
}

func (_c *Aggregator_Add_Call) Return(_a0 bool) *Aggregator_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Aggregator_Add_Call) RunAndReturn(run func(string, string, int64, int64, int64) bool) *Aggregator_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with given fields: ctx, snapshotInterval
func (_m *Aggregator) Run(ctx context.Context, snapshotInterval time.Duration) {
	_m.Called(ctx, snapshotInterval)
}

// Aggregator_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Aggregator_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - snapshotInterval time.Duration
func (_e *Aggregator_Expecter) Run(ctx interface{}, snapshotInterval interface{}) *Aggregator_Run_Call {
	return &Aggregator_Run_Call{Call: _e.mock.On("Run", ctx, snapshotInterval)}
}

func (_c *Aggregator_Run_Call) Run(run func(ctx context.Context, snapshotInterval time.Duration)) *Aggregator_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration))
	})
	return _c
}

func (_c *Aggregator_Run_Call) Return() *Aggregator_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *Aggregator_Run_Call) RunAndReturn(run func(context.Context, time.Duration)) *Aggregator_Run_Call {
	_c.Run(run)
	return _c
}

// Snapshot provides a mock function with no fields
func (_m *Aggregator) Snapshot() *domain.TopSnapshot {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 *domain.TopSnapshot
	if rf, ok := ret.Get(0).(func() *domain.TopSnapshot); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TopSnapshot)
		}
	}

	return r0
}

// Aggregator_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type Aggregator_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
func (_e *Aggregator_Expecter) Snapshot() *Aggregator_Snapshot_Call {
	return &Aggregator_Snapshot_Call{Call: _e.mock.On("Snapshot")}
}

func (_c *Aggregator_Snapshot_Call) Run(run func()) *Aggregator_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Aggregator_Snapshot_Call) Return(_a0 *domain.TopSnapshot) *Aggregator_Snapshot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Aggregator_Snapshot_Call) RunAndReturn(run func() *domain.TopSnapshot) *Aggregator_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// NewAggregator creates a new instance of Aggregator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAggregator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Aggregator {
	mock := &Aggregator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
